# Generated by Django 2.2.12 on 2022-11-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20221101_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('bonus', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodemem', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=50)),
                ('waktu_posting', models.DateTimeField(auto_now_add=True)),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Jenis')),
            ],
        ),
    ]
