# Generated by Django 2.2.12 on 2022-11-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20221120_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='jenis_id',
            new_name='level_id',
        ),
    ]
