# Generated by Django 2.2.12 on 2022-11-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20221120_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='level_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Level'),
        ),
    ]
